// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/tracker/models.proto

package tracker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float32                `protobuf:"fixed32,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_pkg_tracker_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tracker_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_pkg_tracker_models_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_pkg_tracker_models_proto protoreflect.FileDescriptor

const file_pkg_tracker_models_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/tracker/models.proto\x12\atracker\".\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x02R\x03lngB\rZ\vpkg/trackerb\x06proto3"

var (
	file_pkg_tracker_models_proto_rawDescOnce sync.Once
	file_pkg_tracker_models_proto_rawDescData []byte
)

func file_pkg_tracker_models_proto_rawDescGZIP() []byte {
	file_pkg_tracker_models_proto_rawDescOnce.Do(func() {
		file_pkg_tracker_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_tracker_models_proto_rawDesc), len(file_pkg_tracker_models_proto_rawDesc)))
	})
	return file_pkg_tracker_models_proto_rawDescData
}

var file_pkg_tracker_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_tracker_models_proto_goTypes = []any{
	(*Location)(nil), // 0: tracker.Location
}
var file_pkg_tracker_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_tracker_models_proto_init() }
func file_pkg_tracker_models_proto_init() {
	if File_pkg_tracker_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_tracker_models_proto_rawDesc), len(file_pkg_tracker_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_tracker_models_proto_goTypes,
		DependencyIndexes: file_pkg_tracker_models_proto_depIdxs,
		MessageInfos:      file_pkg_tracker_models_proto_msgTypes,
	}.Build()
	File_pkg_tracker_models_proto = out.File
	file_pkg_tracker_models_proto_goTypes = nil
	file_pkg_tracker_models_proto_depIdxs = nil
}
