services:
  postgres:
    extends:
      file: postgres/docker-compose.yml
      service: postgres
  postgres-exporter:
    extends:
      file: postgres/docker-compose.yml
      service: postgres-exporter
  redis:
    extends:
      file: redis/docker-compose.yml
      service: redis
  redis-exporter:
    extends:
      file: redis/docker-compose.yml
      service: redis-exporter
  nginx:
    extends:
      file: nginx/docker-compose.yml
      service: nginx
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    tty: false
  nginx-exporter:
    extends:
      file: nginx/docker-compose.yml
      service: nginx-exporter
  app-1:
    extends:
      file: apps/app/docker-compose.yml
      service: app-1
    ports:
      - 8080:8000
  prometheus:
    extends:
      file: prometheus/docker-compose.yml
      service: prometheus
  node-exporter:
    extends:
      file: prometheus/docker-compose.yml
      service: node-exporter
  grafana:
    extends:
      file: grafana/docker-compose.yml
      service: grafana
  wrk:
    build: wrk
    profiles:
      - manual
    volumes:
      - ./wrk/src:/src
      - ./wrk/data:/data
  wrkx:
    build: wrkx
    platform: linux/amd64
    profiles:
      - manual
    volumes:
      - ./wrk/src:/src
      - ./wrk/data:/data

volumes:
  postgres: {}
  redis: {}
  prometheus: {}

networks:
  macvlan:
    driver: macvlan

