services:
  postgres:
    extends:
      file: postgres/docker-compose.yml
      service: postgres
  postgres-exporter:
    extends:
      file: postgres/docker-compose.yml
      service: postgres-exporter
  redis:
    extends:
      file: redis/docker-compose.yml
      service: redis
  redis-exporter:
    extends:
      file: redis/docker-compose.yml
      service: redis-exporter
  nginx:
    extends:
      file: nginx/docker-compose.yml
      service: nginx
  nginx-exporter:
    extends:
      file: nginx/docker-compose.yml
      service: nginx-exporter
  app-1:
    extends:
      file: app/docker-compose.yml
      service: app-1
    ports:
      - 8080:8080
  app-2:
    extends:
      file: app/docker-compose.yml
      service: app-2
  prometheus:
    extends:
      file: prometheus/docker-compose.yml
      service: prometheus
  node-exporter:
    extends:
      file: prometheus/docker-compose.yml
      service: node-exporter
  grafana:
    extends:
      file: grafana/docker-compose.yml
      service: grafana
  wrk:
    build: wrk
    profiles:
      - manual
  wrkx:
    build: wrkx
    profiles:
      - manual

volumes:
  postgres: {}
  redis: {}
  prometheus: {}
