services:
  nginx:
    image: nginx:1.24
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  nginx-exporter:
    # dashboard id: 12708
    image: nginx/nginx-prometheus-exporter:1.4
    command:
      - '--nginx.scrape-uri=http://nginx:80/stub_status'
    ports:
      - 9113:9113
