services:
  postgres:
    image: postgres:17-alpine
    command: >
      postgres
      -c log_destination=stderr
      -c logging_collector=off
      -c log_statement=ddl
      -c log_min_duration_statement=100
      -c wal_level=logical
      -c max_connections=1000
      -c shared_buffers=4GB
      -c synchronous_commit=on
      -c full_page_writes=on
      -c fsync=on
      -c commit_delay=1000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB}
    ports:
      - 40000:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #       cpus: '2'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  postgres-exporter:
    # dashboard id: 9628
    image: bitnami/postgres-exporter:0.17.1
    restart: on-failure
    environment:
      DATA_SOURCE_NAME: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - 9187:9187
