services:
  redis:
    image: redis:7.4.2
    volumes:
      - redis:/data
      - ./redis.conf:/local/redis/redis.conf
    command: /local/redis/redis.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis-exporter:
    # dashboard id: 11835
    image: bitnami/redis-exporter:1.67.0
    environment:
      REDIS_ADDR: redis://redis:6379
    command: [-debug]
